AllCops:
  Exclude:
    - 'app/bin/*'
    - 'bin/*'
    - 'db/**/*'
    - 'spec/*_helper.rb'
    - 'config/**/*'

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
  
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 130

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'
